# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/checkout@v1
    - name: check for changes
      run: git status
    - name: set author
      run: git config --global user.email "vlaskovic.dodo@gmail.com"
    - name: set author name
      run: git config --global user.name "Dobrosav Vlaskovic"
    - name: ls
      run: ls
    - name: cd
      run: cd ..
    
